trigger: none

resources:
  pipelines:
  - pipeline: BuildPipelineArtifacts
    source: FrontEnd/LandingPage/ContinuousIntegration
    trigger:
      branches:
        include:
        - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - deployment: DeployWebApp
    environment: 'JobMagnetic'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                source: 'specific'
                project: '$(resources.pipeline.BuildPipelineArtifacts.projectID)'
                pipeline: '$(resources.pipeline.BuildPipelineArtifacts.pipelineID)'
                runVersion: 'specific'
                runId: '$(resources.pipeline.BuildPipelineArtifacts.runID)'
                artifactName: 'LandingPage'
                targetPath: '$(Pipeline.Workspace)/downloaded_artifact'

            - task: AzureWebApp@1
              displayName: 'Azure App Service Deploy'
              inputs:
                azureSubscription: 'HasDevWK'
                appType: 'webAppLinux'
                appName: 'JobMagnetic'
                package: '$(Pipeline.Workspace)/downloaded_artifact/$(resources.pipeline.BuildPipelineArtifacts.runID).zip'
                startupCommand: 'node server.js'